filter:
    excluded_paths:
        - 'vendor/*'

checks:
    php:
        code_rating: true

tools:
    external_code_coverage:
        timeout: 1200
        runs: 3
    php_code_coverage: true
    php_code_sniffer:
        config:
            standard: PSR2
    php_loc: true
    php_mess_detector: true
    php_pdepend: true
    php_hhvm: true
    sensiolabs_security_checker: true
