sudo: false

language: php

cache:
    directories:
        - $HOME/.composer/cache

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

matrix:
  allow_failures:
    - php: 7.0
  fast_finish: true
  include:
    - php: 5.3
      env: deps="low"
    - php: 5.6
      env: SYMFONY_VERSION="2.3.x"
    - php: 5.6
      env: SYMFONY_VERSION="2.6.x"
    - php: 5.6
      env: SYMFONY_VERSION="2.7.x"
    - php: 5.6
      env: SYMFONY_VERSION="2.8.x-dev"

before_install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony:"$SYMFONY_VERSION"; fi
  - composer self-update

install:
  - if [ "$deps" = "low" ]; then composer update --prefer-lowest --prefer-stable; else travis_retry composer update $COMPOSER_OPTS; fi

script:
  - if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then phpunit; fi
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpunit --coverage-text --coverage-clover coverage.xml; fi

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi
